version: 2
updates:
  - package-ecosystem: "composer"
    versioning-strategy: increase
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
      - "dependencies"
      - "chore"
    groups:
      composer-require:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      composer-require-dev:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
